name: Format and test EPI

on:
  push:
    branches: 
      - "main"

jobs:
  ruff:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Format & fix
        uses: chartboost/ruff-action@v1
        with:
          args: "check --fix"
